baseURL = "https://sean.burlington.me.uk/"
languageCode = "en-gb"
title = "Some thoughts"
theme = "sean"
uglyurls = true

[params]
  favicon = ""
  description = ""

  twitter = "https://twitter.com/seanburlington"


  github = "https://github.com/seanburlington"

  linkedin = "https://www.linkedin.com/in/seanburlington/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-green"
 # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 5
  uglyurls = true # this settings is duplicated here so that it is available in templates
  custom_css = ['sean.css']


[markup]
  [markup.goldmark.renderer]
   unsafe= true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "solarized-dark"
    tabWidth = 4