baseURL = "http://sean.burlington.me.uk/"
languageCode = "en-gb"
title = "Some thoughts"
theme = "ananke"
uglyurls = true

[params]
  favicon = ""
  description = ""

  twitter = "https://twitter.com/seanburlington"


  github = "https://github.com/seanburlington"

  linkedin = "https://www.linkedin.com/in/seanburlington/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-green"
 # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 5
  uglyurls = true

